# Copyright (c) 2020 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.


title: "OCloud Framework"
description: "Oracle Resource Manager Stack"
stackDescription: "ITIL inspired service delivery framework for application deployments in Oracle Cloud Infrastructure (OCI)"
schemaVersion: 1.1.0
version: "20212409"
locale: "en"

variableGroups:
- title: "Hidden Configuration"
  visible: false
  variables:
  - tenancy_ocid
  - compartment_ocid
  - region
  
- title: "General Configuration"
  visible: true
  variables:
  - organization
  - project
  - environment
  - code_source

- title: "Notifications"
  visible: true
  variables:
  - admin_mail
  #- slack_channel

- title: "Sections"
  visible: false
  variables:
  - operation
  - network
  - database
  - application

variables:
  # Hidden Configuration
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier (OCID) for your tenancy"
    type: string
    required: true
    visibile: false

  compartment_ocid:
    title: "Compartment ID"
    description: "The Oracle Cloud Identifier (OCID) for your compartment"
    type: string
    required: true
    visibile: false

  region:
    title: "Home Region"
    description: "The Oracle Cloud Identifier (OCID) for your home region"
    type: string
    required: true
    visibile: false

  # General Configuration
  organization:
    title: "Organization"
    description: "Identifier for the organization or platform owner"
    type: string
    required: true
    visibile: true

  project:
    title: "Project or Program"
    description: "Identifier for the service delivery platform"
    type: string
    required: true
    visibile: true

  environment:
    title: "Environment"
    description: "Define the CI/CD process stage, e.g. dev, uat, prod"
    type: string
    required: true
    visibile: true

  code_source:
    title: "Source"
    description: "Provide an URL to your source repository"
    type: string
    required: true
    visibile: true

  # Notifications
  admin_mail:
    title: "eMail"
    description: "Provide an eMail address for the technical administrator of your project"
    type: string
    required: true
    visibile: true

  #slack_channel:
    #title: "Slack"
    #description: "Provide a web hook for the slack channel, used for the project"
    #type: string
    #required: false
    #visibile: true

  # Sections
  operation:
    title: "Operation Section"
    description: "The identifier for your Operation Compartment"
    type: string
    required: false
    visibile: false

  network:
    title: "Network Section"
    description: "The identifier for your Network Compartment"
    type: string
    required: false
    visibile: false

  database:
    title: "Database Section"
    description: "The identifier for your Database Compartment"
    type: string
    required: false
    visibile: false

  application:
    title: "Application Section"
    description: "The identifier for your Application Compartment"
    type: string
    required: false
    visibile: false